### ISSUE TITLE
Group / Members tab has error if you delete a user in the Dashboard that's been assigned to the group

### ISSUE THREAD

**Issue by twistedstream** [auth0/auth0-authorization-extension#123]
Steps to reproduce:

1. Create a new user in the Auth0 Dashboard
2. Assign that user to a group in the extension
3. Delete the user in the Dashboard
4. Navigate to the group's Members tab and you'll see an error like this:

![image](https://cloud.githubusercontent.com/assets/3535918/20847250/e55d49a4-b892-11e6-9dd7-dd1f3048df2c.png)

Obviously the extension doesn't know when a user it's managing has been deleted from Auth0. It needs to be able to tolerate this and perhaps remove the user from its store when this is detected, although I don't like changing state (eg. remove a user) as the result of a query.

**Comment by kmckenney** [comment]
To add to this...
The same error is emitted by the '/api/group/[group_id]/members' API of the Authorization extension (the likely source of errors displayed on the UI) under these conditions. Ideally the deletion of a user in Auth0 could trigger clean-up in the Group/Roles stores for the extension as well. If not feasible, the API should at least tolerate it in such a way that the group can be repaired from the API. The current behavior doesn't even allow an API user to discover the problem userid in order to remove it.

**Comment by sandrinodimattia** [comment]
The update will make sure that deleted members still show up. This will give you an opportunity to remove them from the group:

![image](https://cloud.githubusercontent.com/assets/655409/21384483/0e1e5b9e-c76b-11e6-8bda-08bfcddd36ad.png)
